export declare const MSG_STATUS_FAILED = -100;
export declare const MSG_STATUS_SENDING = 0;
export declare const MSG_STATUS_SENT = 100;
export declare const MSG_STATUS_SENT_SERVER = 150;
export declare const MSG_STATUS_RECEIVED = 200;
export declare const MSG_STATUS_RETURN_RECEIPT = 250;
export declare const MSG_STATUS_SEEN = 300;
export declare const MIN_HEIGHT_TEXTAREA: number;
export declare const MAX_HEIGHT_TEXTAREA: number;
export declare const PARENT_PAGE_USERS: string;
export declare const PARENT_PAGE_DETAIL_CONVERSATION: string;
export declare const BCK_COLOR_CONVERSATION_SELECTED: string;
export declare const BCK_COLOR_CONVERSATION_UNSELECTED: string;
export declare const TYPE_SUPPORT_GROUP: string;
export declare const TYPE_MSG_TEXT: string;
export declare const TYPE_MSG_IMAGE: string;
export declare const MAX_WIDTH_IMAGES: number;
export declare const TYPE_DIRECT: string;
export declare const TYPE_GROUP: string;
export declare const SYSTEM: string;
export declare const URL_NO_IMAGE: string;
export declare const LABEL_NOICON: string;
export declare const CLIENT_BROWSER: string;
export declare const TYPE_POPUP_LIST_CONVERSATIONS: string;
export declare const TYPE_POPUP_DETAIL_MESSAGE: string;
